#!/bin/sh
mkdir -p ./src/main/java
mkdir -p ./src/main/scala
mkdir -p ./src/main/kotlin
mkdir -p ./src/main/resources
mkdir -p ./src/test/java
mkdir -p ./src/main/scala
mkdir -p ./src/main/kotlin
mkdir -p ./src/test/resources
mkdir -p ./src/dist/


