#!/bin/sh

setenv(){
    export MDB_HOME=/home/bin/mariaDB/mariadb
    export PATH=$MDB_HOME/bin:$PATH
   echo "set mariadb env success: "$MDB_HOME
}

if [ -z $1 ]; then
   setenv
else
if [ -z $MDB_HOME ]; then
   setenv
fi
cd $MDB_HOME
case "$1" in
	start)
		echo "start mariaDB..."
		./bin/mysqld_safe &
		echo "mariaDB start success."
	;;
	stop)
		echo "stop mariaDB..."
		./bin/mysqladmin shutdown -uroot -p
		echo "mariaDB stop success."
	;;
	*)
		echo "Usage: `basename $0` start|stop"
#		exit 1
esac

fi

