#!/bin/bash
#
# /etc/init.d/oracledb
#
# Run-level Startup script for the Oracle Listener and Instances
# It relies on the information on /etc/oratab
source oracle.sh
export ORACLE_OWNR=sren

if [ ! -f $ORACLE_HOME/bin/dbstart -o ! -d $ORACLE_HOME ]
then
    echo "Oracle startup: cannot start"
    exit 1
fi

case "$1" in
    start)
        # Oracle listener and instance startup
        echo -n "Starting Oracle: "
        $ORACLE_HOME/bin/lsnrctl start
        $ORACLE_HOME/bin/dbstart $ORACLE_HOME
        touch $ORACLE_HOME/oracle.lock
        echo "OK"
        ;;
    stop)
        # Oracle listener and instance shutdown
        echo -n "Shutdown Oracle: "
        $ORACLE_HOME/bin/lsnrctl stop
        $ORACLE_HOME/bin/dbshut $ORACLE_HOME
        rm -f $ORACLE_HOME/oracle.lock
        echo "OK"
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: `basename $0` start|stop|restart|reload"
        exit 1
esac

exit 0
