#!/bin/bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en

# set XILINX_USB_DEV="002:003" for multiple USB port
echo "use XILINX_USB_DEV=\"002:024\" to use more than 1 impact"
xilinx=/home/bin/xilinx/14.7/ISE_DS
export LD_PRELOAD=/home/bin/libusb/libusb-driver.so
source $xilinx/settings64.sh



if [ -z $1 ];
then
	echo "useage: "
	echo "    xilinx ise"
	echo "    xilinx analyzer"
	echo "    xilinx impact"
	echo "    xilinx unlock"
	echo "    ...."
else
	if [ "$1" == "unlock" ]; then
		$xilinx/ISE/bin/lin64/impact -batch /home/bin/0bin/xilinx.unlock
	else
		$xilinx/ISE/bin/lin64/$@ &
	fi
fi

