#!/bin/sh
server=$(basename $0)
source db19dev
source esb
source vegaps


IP=10.10.52.17
ESBPORT=8788
PRJS=(ESB ESBJMS ESBQueue_Exception ESBQueue_ExManual ESBQueue_Reverse ESBQueue_Resend ESBJMS_Log ESBJMS_PCP_INF ESBJMS_PCP_COM ESBJMS_PCP_REAL ESBJMS_TCBS ESBJMS_PMS)



