#!/bin/zsh
work=$(basename $0)
source oracle.sh
source vegaps


if [ ! $dbUrl ];
	then
	echo "dbUrl not set"
fi


logError(){
execSql "UPDATE VPM_APP_PARAMETERS SET VALUE='ERROR' WHERE code='ESB_LOG_LEVEL';"
}
logInfo(){
execSql "UPDATE VPM_APP_PARAMETERS SET VALUE='INFO' WHERE code='ESB_LOG_LEVEL';"
}
logDebug(){
execSql "UPDATE VPM_APP_PARAMETERS SET VALUE='DEBUG' WHERE code='ESB_LOG_LEVEL';"
}

noFileLog(){
execSql "update vpm_app_parameters t set t.value='N' where t.code='ESB_IS_LOG_FILELOG';"
}
fileLog(){
execSql "update vpm_app_parameters t set t.value='Y' where t.code='ESB_IS_LOG_FILELOG';"
}

noDbLog(){
execSql "update vpm_app_parameters t set t.value='N' where t.code='DB_LOG_DIP';"
}
dbLog(){
execSql "update vpm_app_parameters t set t.value='Y' where t.code='DB_LOG_DIP';"
}

testNone(){
execSql "update vpm_app_parameters t set t.value='N' where t.code='DB_LOG_DIP';
update vpm_app_parameters t set t.value='N' where t.code='ESB_IS_LOG_FILELOG';
update vpm_app_parameters t set t.value='ERROR' where t.code='ESB_LOG_LEVEL';
update vsr_service_executor t set t.is_enable='N' where t.name in ('ServiceRequestTransformer', 'ServiceResponseTransformer');"
}

testAll(){
execSql "update vpm_app_parameters t set t.value='Y' where t.code='DB_LOG_DIP';
update vpm_app_parameters t set t.value='Y' where t.code='ESB_IS_LOG_FILELOG';
update vpm_app_parameters t set t.value='ERROR' where t.code='ESB_LOG_LEVEL';"
}

noTrans(){
execSql "update vsr_service_executor t set t.is_enable='N' where t.name in ('ServiceRequestTransformer', 'ServiceResponseTransformer');"
}
trans(){
execSql "update vsr_service_executor t set t.is_enable='Y' where t.name in ('ServiceRequestTransformer', 'ServiceResponseTransformer');"
}  

testDB(){
execSql "select sysdate from dual;"
}


execSqlFile(){
if [ ! $1 ];
	then
		echo "useage: dbopt execSqlFile [sqlFile]"
	else
		source oracle.sh
		echo $dbUrl
		echo "execute sql file: "$1
		sqlplus -S $dbUrl @$1
fi
}

execSql(){
if [ ! $1 ];
	then
		echo "no sql to exec"
		goto end
	else
source oracle.sh
echo $dbUrl
echo "execute sql: "$1
sqlplus -S $dbUrl <<EOF
set autocommit on;
$1
set autocommit off;
exit
EOF

fi
}


$1
