#!/usr/bin/python
import socket, sys
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((sys.argv[1], int(sys.argv[2])))
print("connected")
#`data = sys.stdin.readline().strip()
s.sendall(sys.argv[3].encode('utf-8'))
print(s.recv(100))
s.close()


