#!/bin/sh

IPPORT=$IP:$ESBPORT
TESTXMLHOME=/home/vega/ESB/esbDev/src/dev_xib/test/resource/request/

all(){
stopAll
ant
up
startAll
test
}

up(){
scp $VEGA_HOME/lib/vsr-esb.jar $TGT:vegahome/lib/
}

stop(){
echo "try to stop project /Projects/$1/initial on $TGT"
ssh $TGT "bash -c 'vtadmin stop project /Projects/$1/initial'" &
}

start(){
echo "try to start project /Projects/$1/initial on $TGT"
ssh $TGT "bash -c 'vtadmin start project /Projects/$1/initial'" &
}

stopAll(){
for i in $PRJS; do
   stop $i 
done 
}

startAll(){
for i in $PRJS; do
  start $i
done
}

test(){
export DATA="$(cat $TESTXMLHOME/test1.xml)"
echo "invoke ESB http port by xml:"
echo $DATA
curl http://$IPPORT/ESB-initial/http -d "${DATA}"
}

testUnionApi(){
export DATA="$(cat $TESTXMLHOME/UnionAPI_req.xml)"
curl http://$IPPORT/ESB-initial/http -d "${DATA}"
}

testUnionApi2(){
export DATA="$(cat $TESTXMLHOME/UnionAPI_req2.xml)"
curl http://$IPPORT/ESB-initial/http -d "${DATA}"
}

refresh(){
curl http://$IPPORT/ESB-initial/sys -d "<request action=\"refreshAll\" />"
}

